[package]
name = "min_game"
version = "0.1.0"
authors = ["zaimoni <tharichizi@gmail.com>"]
edition = "2018"

[features]
Async = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
rand_xoshiro = "0.4.0"
tcod = "0.15.0"