[package]
name = "min_game"
version = "0.1.0"
authors = ["zaimoni <tharichizi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tcod = "0.15.0"